export const upwork =[
    {
        "Title": "\n            Android Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~014970392125b0633d?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1Li6Z2lUjjZAej48qriK08N4LfGPNYi6KrQa1kUJeZ299Os0CHSNHqZzOKi2drBzZ",
        "Name": "\n            Atendra S.\n          ",
        "Location": "\n          India\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$20",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          96%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $50K+ earned\n    ",
        "air3badge": "\n  Available now\n",
        "air3tokenwrap": "\n      Smartphone\n    ",
        "air3tokenwrap2": "\n      Android\n    ",
        "air3tokenwrap3": "\n      Android App Development\n    ",
        "air3tokenwrap4": "\n      Java\n    ",
        "air3tokenwrap5": "\n      Kotlin\n    ",
        "air3tokenwrap6": "\n      Mobile App Development\n    ",
        "air3tokenwrap7": "\n      Firebase\n    ",
        "air3token": "+10",
        "Description": "\n      🌟 Top-Rated Upwork Professional 🧑🏻‍💻 9+ years of experience 📱 Android | Kotlin | Java | Jetpack Compose | Kotlin-Multiplatform| Flutter | WearOS | AndroidTV | 🚀 AI | ChatGPT | 💻 Firebase | VoIP | Linphone\n\nWith over 9 years of extensive experience as an Android Developer, I specialize in native Android application programming with a strong focus on SCRUM/Agile workflow. \n\nI have a proven track record of delivering high-quality mobile applications in various domains, including:\n\n* Airline Domain\n* Banking Domain\n* Cargo Management Domain\n* Logistics Domain\n* Financial Domain\n* Social Media/Dating Domain with Video/Audio Chats\n* Location Tracking Domain\n\nMy expertise in mobile development includes:\n\n* Programming Languages: Java, Kotlin\n* Architectural Patterns: MVVM, MVP, MVC\n* Design Patterns, Custom Controls, and REST API integration\n* Material Design, Mobile UI/UX, and Firebase integration (AdMob, Analytics, A/B testing, etc.)\n* Jetpack Compose, Jetpack Navigation\n* Firebase Realtime Database and Storage\n* Android SDK, NDK, Open Source, Support Libraries\n* Reactive Programming with rxJava and rxAndroid\n* Dependency Injection using Dagger, Kodein, and Hilt\n* Databases: SQLite, Room, Realm, Page\n* Network Libraries: Retrofit, OkHttp, Volley, ktor\n* Image Loading Libraries: Picasso, Glide\n* Crash Reporting and Analytics Tools: Crashlytics, Firebase, Fabric, LeakCanary, Timber\n* Other Libraries: Gson, AutoValue, JodaTime, AndroidJob, Google Services\n* Sockets/SignalR\n* Kiosk Mode\n* SonarQube code coverage\n* Kotlin-Multiplatform (One POC)\n* Wear OS & Smartwatch development\n* Mqtt\n\nIn addition, I am an expert in the Linphone SDK, a powerful tool for building voice and video communication applications. I have in-depth knowledge of integrating and customising the Linphone SDK to create high-quality, real-time voice and video chat functionalities within Android applications. I am experienced in implementing Linphone's advanced features, including call management, audio/video codecs, encryption, push notifications, and more. Whether you need to develop a VoIP application from scratch or enhance an existing app with Linphone capabilities, I can provide the expertise you require.\n\nI have integrated various features and technologies into Android applications, including:\n\n* Beacons integration for proximity-based interactions\n* Calendar API integration for managing events and schedules\n* QR Code integration for scanning and processing QR codes\n* OCR (Optical Character Recognition) integration for text recognition and extraction\n\nFor multimedia capabilities, I have integrated Video Chat using WebRTC, ZegoClould, Twilio, and Agora, as well as Audio Streaming. I am familiar with ExoPlayer for HLS Video Streaming (HTTP Video Streaming), RTSP Video Streaming, and DASH Video Streaming.\n\nOther skills and features I offer include Custom Calendar development, Media Gallery implementation, Background Download and Upload functionality, Tiff file format handling in Android, Live Streaming using Agora and ZegoCloud SDK, Deep Linking, LeakCanary for memory leak detection, and code annotations to improve the linting process.\n\nExperienced Kotlin Multiplatform Developer with a track record of delivering efficient cross-platform solutions. Proficient in Kotlin Multiplatform Mobile (KMM) and skilled in creating high-performance apps for Android, iOS, web, and more. \n\nExperienced Jetpack Compose Developer, proficient in creating dynamic, interactive, and modern Android UIs. Skilled in leveraging Jetpack Compose's power to build visually stunning and responsive applications. \n\nOver the years, I have developed many different types of iPhone and Android apps. These include:\n- Food delivery apps\n- On-demand apps\n- Home services apps\n- Handy man apps\n- Salon apps\n- Beauty apps\n- Taxi apps\n- Ride apps\n- E-commerce apps\n- Dating apps\n- Health and fitness apps\n- Travel apps\n- Video streaming apps\n- Fintech apps\n- Shopping apps\n- Telemedicine apps\n- Finance apps\n- Real estate apps\n- Social media apps\n- Chat apps\n- Business apps\n- Messaging apps\n- Online courses apps\n- Online education learning apps\n- Tutor apps\n- Hotel booking apps\n- Online grocery order apps\n- Telecommunication apps\n- VoIP apps\n- SIP Apps\n- Apps using the Twilio API\n\nI am fluent in English and passionate about Android development. Please feel free to reach out to me with any Android-related questions or projects. I would be pleased to help you bring your ideas to life.\n    ",
        "upporti18n": "\n          Atendra S.\n        \n        has worked\n      ",
        "air3btn8": "\n        17 jobs related to your search\n      ",
        "Avatar9": "https://assets.static-upwork.com/org-logo/1419972262982979584",
        "textbasesm": "Associated with",
        "Name10": "\n          Hastree Technologies Pvt Ltd\n        ",
        "dflex": "$100K+",
        "air3tokenwrap11": "\n      VoIP\n    "
    },
    {
        "Title": "\n            Android Developer | Web Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~01be37a1e053a7741d?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1ry3Kpo0fj6EG9QekI2U6mNYb8fH71SZzkxq8p_vmETRwQlSKVL9u_rdqc4z_Hjsw",
        "Name": "\n            Mahmoud A.\n          ",
        "Location": "\n          Egypt\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$40",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $7K+ earned\n    ",
        "air3badge": "",
        "air3tokenwrap": "\n      Android App Development\n    ",
        "air3tokenwrap2": "\n      Java\n    ",
        "air3tokenwrap3": "\n      Kotlin\n    ",
        "air3tokenwrap4": "\n      Mobile App Development\n    ",
        "air3tokenwrap5": "\n      Firebase\n    ",
        "air3tokenwrap6": "\n      In-App Purchases\n    ",
        "air3tokenwrap7": "\n      SQLite\n    ",
        "air3token": "+10",
        "Description": "\n      Student at EELU university , Information technology branch\n\nANDROID TECH STACK  :\nAndroid Kotlin,Java : Retrofit , Rest APIs , Material UI , TensorFlow lite Integration , Firebase , AdMob , Google In App Purchases , Google Maps , AR , Bluetooth and More\n\nWEB TECH STACK : \nHTML, CSS, Javascript\nMERN stack : Node.js , Express , Mongodb , React.js\n\n\n    ",
        "upporti18n": "\n          Mahmoud A.\n        \n        has worked\n      ",
        "air3btn8": "\n        6 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      JavaScript\n    "
    },
    {
        "Title": "\n            Senior / Lead Android Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~018e803713cc6aec2e?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1bh-1JbsuRT9tRdsi-Duw96BaYHqMtU8FsHjbPtPrcOoI5gkmM45w--DnYQjiJQz0",
        "Name": "\n            Oleg S.\n          ",
        "Location": "\n          Ukraine\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$63",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "",
        "air3badge": "",
        "air3tokenwrap": "\n      Smartphone\n    ",
        "air3tokenwrap2": "\n      Android\n    ",
        "air3tokenwrap3": "\n      Java\n    ",
        "air3tokenwrap4": "\n      Kotlin\n    ",
        "air3tokenwrap5": "\n      Native App Development\n    ",
        "air3tokenwrap6": "\n      Tablet\n    ",
        "air3tokenwrap7": "\n      Firebase\n    ",
        "air3token": "+3",
        "Description": "\n      A self-taught, purposeful, and enthusiastic software engineer with 9+ years of practical experience, specializing in Java, Android, Kotlin, automated testing, Team Leadership, and Agile methodologies. I head the Android department in New Line Technologies, and my responsibilities include developing and supporting software, communicating with customers, and mentoring subordinate developers.\n\nI have extensive experience in\n* the independent development of Android projects from scratch to app release on Google Play.\n* e-commerce projects.\n* work with AI models (TensorFlow, ONNX)\n* multi-media projects: live video streaming (using RTMP, UDP), video processing in real-time, video post-processing.\n* using devices hardware: WiFiDirect, Bluetooth, magnetometer, GPS.\n* work with a Bitcoin protocol, a Dash protocol, and a Bitcore wallet service/client.\n* large projects with globally distributed teams.\n* mentoring, code refactoring, troubleshooting, optimizing, and performance tuning.\n\nI became the Android team leader in only a year and a half due to my passion for software development and my skills in solving challenging tasks.\n\nIn my spare time, you can find me in a gym squatting with a bar, playing with my son, or reading self-improvement books.\n    ",
        "upporti18n": "\n          Oleg S.\n        \n        has worked\n      ",
        "air3btn8": "\n        10 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      User Profile Creation\n    "
    },
    {
        "Title": "\n            Top Rated Mobile App Developer | iOS Developer | Android Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~014240eb1d96f9bae2?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1w_cLACzH-b8Kxu1UxajJ8M8zgWiEA_B9U6WmhCublQPeMydnuBYgGO3R4IwhjIwY",
        "Name": "\n            Daxesh P.\n          ",
        "Location": "\n          India\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$24.99",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $900K+ earned\n    ",
        "air3badge": "\n  Available now\n",
        "air3tokenwrap": "\n      Android\n    ",
        "air3tokenwrap2": "\n      Android App Development\n    ",
        "air3tokenwrap3": "\n      Kotlin\n    ",
        "air3tokenwrap4": "\n      Mobile App Development\n    ",
        "air3tokenwrap5": "\n      Flutter\n    ",
        "air3tokenwrap6": "\n      Node.js\n    ",
        "air3tokenwrap7": "\n      PHP\n    ",
        "air3token": "+10",
        "Description": "\n      ✅  Rewarded as 🏆 𝗧𝗢𝗣 𝗥𝗔𝗧𝗘𝗗 𝗣𝗟𝗨𝗦 🏆 by Upwork (𝗧𝗼𝗽 𝟯%)\n✅  10000+ hours and still counting \n✅  200+ jobs completed successfully \n✅  100% Job Success (Client Satisfaction Ratio)\n✅  Clutch Award Winner - 2022\n✅  Tech Behemoths Awards Winner - 2023\n✅  TrueFirms Award Winner - 2024\n✅  90% Clients Recommended to work with me\n✅  86% Long-term Repeat Clients\n✅  12+ Years Of Experience\n✅  High-Quality Work\n✅  Budget-friendly\n✅  Fluent English Verified\n\nWhether you are a 𝗦𝘁𝗮𝗿𝘁𝘂𝗽, 𝗘𝘀𝘁𝗮𝗯𝗹𝗶𝘀𝗵𝗲𝗱 𝗕𝘂𝘀𝗶𝗻𝗲𝘀𝘀 or looking for 𝗠𝗩𝗣, you will get 𝗛𝗶𝗴𝗵-𝗤𝘂𝗮𝗹𝗶𝘁𝘆 𝗦𝗲𝗿𝘃𝗶𝗰𝗲𝘀 at an 𝗔𝗳𝗳𝗼𝗿𝗱𝗮𝗯𝗹𝗲 𝗖𝗼𝘀𝘁, 𝗚𝘂𝗮𝗿𝗮𝗻𝘁𝗲𝗲𝗱.💯\nInterested? Just click on the '𝗜𝗻𝘃𝗶𝘁𝗲 𝘁𝗼 𝗝𝗼𝗯' button and let’s discuss your project and your vision.🤝\n\nMY UPWORK CLIENTS SHARING THEIR EXPERIENCE WORKING WITH ME:\n\n★★★★★ 5.00\n\"Daxesh and his team are amazing. They are super customer oriented, very friendly, easy to work with and very experienced and skilled. We will for sure engage them again and I can 100% recommend him to work with. The best freelancer / agency on Upwork I have worked with so far.\"\n- Christian, Germany\n\n★★★★★ 5.00\n\"Daxesh and his team were incredibly skilled, thoughtful, and responsive throughout the entire project! I couldn't have asked for a better team of developers to work with, and I greatly look forward to working with them again in the near future.\"\n- Aimun, USA \n\n★★★★★ 5.00\n\"Exceeds expectations and always a great experience. Even with an extended break between jobs, picked up where we left off with no problems whatsoever.\"\n- Beau, Canada\n\nThese are some testimonials taken directly from my Upwork profile 𝗽𝗿𝗼𝘃𝗲 that 𝗜 𝗰𝗮𝗻 𝗱𝗲𝗹𝗶𝘃𝗲𝗿 𝘁𝗵𝗲 𝗽𝗿𝗼𝗱𝘂𝗰𝘁 𝘄𝗶𝘁𝗵 𝗴𝗿𝗲𝗮𝘁 𝗾𝘂𝗮𝗹𝗶𝘁𝘆 𝗼𝗻 𝘁𝗶𝗺𝗲 𝘄𝗶𝘁𝗵 𝘇𝗲𝗿𝗼 𝘄𝗼𝗿𝗿𝗶𝗲𝘀. \n\nFor me, 𝗖𝗟𝗜𝗘𝗡𝗧 𝗦𝗔𝗧𝗜𝗦𝗙𝗔𝗖𝗧𝗜𝗢𝗡 𝗖𝗢𝗠𝗘𝗦 𝗙𝗜𝗥𝗦𝗧.🎯\n\nDuring the last 11+ years, I have developed many different types of iOS and Android apps.\n𝗙𝗼𝗼𝗱 𝗱𝗲𝗹𝗶𝘃𝗲𝗿𝘆 𝗮𝗽𝗽, 𝗢𝗻-𝗱𝗲𝗺𝗮𝗻𝗱 𝗔𝗽𝗽, 𝗛𝗼𝗺𝗲 𝘀𝗲𝗿𝘃𝗶𝗰𝗲𝘀 𝗮𝗽𝗽, 𝗛𝗮𝗻𝗱𝘆 𝗺𝗮𝗻 𝗮𝗽𝗽, 𝗠𝗮𝗿𝗸𝗲𝘁𝗽𝗹𝗮𝗰𝗲 𝗮𝗽𝗽, 𝗦𝗮𝗹𝗼𝗻 𝗮𝗽𝗽, 𝗕𝗲𝗮𝘂𝘁𝘆 𝗮𝗽𝗽, 𝗧𝗮𝘅𝗶 𝗮𝗽𝗽, 𝗥𝗶𝗱𝗲 𝗮𝗽𝗽, 𝗘-𝗰𝗼𝗺𝗺𝗲𝗿𝗰𝗲 𝗮𝗽𝗽, 𝗗𝗮𝘁𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗛𝗲𝗮𝗹𝘁𝗵 𝗮𝗻𝗱 𝗳𝗶𝘁𝗻𝗲𝘀𝘀 𝗮𝗽𝗽, 𝗧𝗿𝗮𝘃𝗲𝗹 𝗮𝗽𝗽, 𝗟𝗶𝘃𝗲 𝗦𝘁𝗿𝗲𝗮𝗺𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗩𝗶𝗱𝗲𝗼 𝘀𝘁𝗿𝗲𝗮𝗺𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗙𝗶𝗻𝘁𝗲𝗰𝗵 𝗮𝗽𝗽, 𝗦𝗵𝗼𝗽𝗽𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗧𝗲𝗹𝗲𝗺𝗲𝗱𝗶𝗰𝗶𝗻𝗲 𝗮𝗽𝗽, 𝗙𝗶𝗻𝗮𝗻𝗰𝗲 𝗔𝗽𝗽, 𝗥𝗲𝗮𝗹 𝗲𝘀𝘁𝗮𝘁𝗲 𝗮𝗽𝗽, 𝗦𝗼𝗰𝗶𝗮𝗹 𝗺𝗲𝗱𝗶𝗮 𝗮𝗽𝗽, 𝗖𝗵𝗮𝘁 𝗮𝗽𝗽, 𝗕𝘂𝘀𝗶𝗻𝗲𝘀𝘀 𝗮𝗽𝗽, 𝗠𝗲𝘀𝘀𝗮𝗴𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗢𝗻𝗹𝗶𝗻𝗲 𝗲𝗱𝘂𝗰𝗮𝘁𝗶𝗼𝗻 𝗹𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗛𝗼𝘁𝗲𝗹 𝗯𝗼𝗼𝗸𝗶𝗻𝗴 𝗮𝗽𝗽, 𝗚𝗿𝗼𝗰𝗲𝗿𝘆 𝗼𝗿𝗱𝗲𝗿 𝗮𝗽𝗽, 𝗔𝗜 𝗖𝗵𝗮𝘁𝗯𝗼𝘁, 𝗔𝗜 𝗪𝗲𝗹𝗹𝗻𝗲𝘀𝘀 𝗮𝗽𝗽, 𝗔𝗜 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗮𝗽𝗽, and many more.\n\n🔹 By working with me, 𝗬𝗼𝘂'𝗹𝗹 𝘂𝗻𝗹𝗼𝗰𝗸:🚀\n✔ Your Reliable Partner: I always work towards your success\n✔ Tech Expert for 12+ Years: Strong Android, iOS, and backend knowledge\n✔ Quality Work, Affordable Prices: Creative and budget-friendly solutions\n✔ Proven Track Record: Successfully built many high-quality apps\n✔ Honest and Transparent Practices: No secrets, No unethical things, Just results\n✔ Prompt Communication: Keeps you updated all the way\n✔ Timely Delivery: Deliver Apps on time\n✔ Latest Trends: Up-to-date with the latest technologies\n\n🔹 My core skills and experiences:🔥\n◉ Interaction with backend - Rest API, JSON, XML\n◉ Social Integration – Facebook, Twitter, Instagram, Google, Apple\n◉ Chat - XMPP, Socket, Firebase, GetStream, Twilio, Agora\n◉ Version Control Tools - Github, BitBucket, GitLab\n◉ Google Maps, Apple Map kit, Geolocation, GPS, Location Tracking\n◉ Audio / Video Live Streaming\n◉ Firebase, FCM, FireStore, Firebase Analytics \n◉ Paypal, Stripe, Square Payment Gateway\n◉ QR Codes, Bar Codes, VIN, NFC Tags Reading\n◉ In-app subscriptions, Ads, Push Notifications, Google Analytics\n◉ Photo & Video Sharing, Editor, Filter\n◉ AI, ChatGPT, OpenAI, AI chatbots\n\n🔹 We work with the below technologies for development:📱💻\n𝗔𝗻𝗱𝗿𝗼𝗶𝗱: Kotlin, Java, Jetpack compose\n𝗶𝗢𝗦: Swift, Objective-C, SwiftUI\n𝗖𝗿𝗼𝘀𝘀-𝗽𝗹𝗮𝘁𝗳𝗼𝗿𝗺 (𝗛𝘆𝗯𝗿𝗶𝗱): Flutter (Dart)\n𝗪𝗲𝗯 / 𝗕𝗮𝗰𝗸𝗲𝗻𝗱: Node.js, Express.js, Nest.js, PHP, Laravel, WordPress, Python, Django\n𝗙𝗿𝗼𝗻𝘁𝗲𝗻𝗱: React.Js, HTML5, CSS3, BootStrap, JavaScript, jQuery\n𝗗𝗮𝘁𝗮𝗯𝗮𝘀𝗲𝘀: SQLite, MySQL, MongoDB, PostgreSQL\n𝗟𝗮𝘁𝗲𝘀𝘁 𝗧𝗿𝗲𝗻𝗱𝘀: Artificial Intelligence (AI), Augmented Reality (AR), Internet Of Things (IoT)\n\n💬 𝗙𝗥𝗘𝗘 𝗖𝗢𝗡𝗦𝗨𝗟𝗧𝗔𝗧𝗜𝗢𝗡: \nMy consultation is 𝗙𝗥𝗘𝗘. Let's schedule an introductory call and discover the possibilities of working together. \nEven if we don't work together, you will get some tips/ideas that can be helpful to your project.\nJust click on the '𝗜𝗻𝘃𝗶𝘁𝗲 𝘁𝗼 𝗝𝗼𝗯' button and experience yourself.🙌\n\nThank you for spending your $$ to review my profile because TIME IS MONEY :)\n    ",
        "upporti18n": "\n          Daxesh P.\n        \n        has worked\n      ",
        "air3btn8": "\n        33 jobs related to your search\n      ",
        "Avatar9": "https://assets.static-upwork.com/org-logo/1459027205034774528",
        "textbasesm": "Associated with",
        "Name10": "\n          iRoid Solutions | Upwork Top Rated Agency | Clutch 2022 Award Winner | TechBehemoths 2023 Award Winner IT Company\n        ",
        "dflex": "",
        "air3tokenwrap11": "\n      Swift\n    "
    },
    {
        "Title": "\n            iOS, Swift,Flutter, Android, Java Developer, React Native, Web.\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~01e19fb95a97128be7?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1QLx8v2OonGpsnxGyXQBYWCD1L2lK6F8ECnmabWHpX_1YV3jYhYMhR4Bitw9Gz7n6",
        "Name": "\n            Taimur I.\n          ",
        "Location": "\n          India\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$25",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $400K+ earned\n    ",
        "air3badge": "",
        "air3tokenwrap": "\n      Android\n    ",
        "air3tokenwrap2": "\n      Android App Development\n    ",
        "air3tokenwrap3": "\n      Android SDK\n    ",
        "air3tokenwrap4": "\n      Java\n    ",
        "air3tokenwrap5": "\n      Mobile App Development\n    ",
        "air3tokenwrap6": "\n      Objective-C\n    ",
        "air3tokenwrap7": "\n      Swift\n    ",
        "air3token": "+6",
        "Description": "\n      ⚫️🟣⚫️🟣⚫️🟣⚫️ \n\n10+ Years of Experience in Mobile Apps Development \n\n(NO UPFRONT PAYMENTS needed)\n\n💰 TOP-RATED PLUS by Upwork 💲300000+ TOTAL EARNINGS 🤑 \n🚀🚀🚀 FAST PROJECT DELIVERY.\n\n 🚚🚚, 500+ client testimonials ⭐⭐⭐ ⭐ ⭐ and a 100 % Success rate 🙌🙌 \n\n⚫️🟣⚫️🟣⚫️🟣⚫️ \n\n\nI  am a mobile application developer. I develop iOS, Android, Rect Native and PHP. I have developed more than 100 apps which are available in the market. I provide quality works. I take care of everything about the app. I will provide support forever what I develop.\n\nWhy to select me?\n\n   ✅   I am top rated on Upwork.\n   ✅   3500+ hours completed \n   ✅   100+ Mobile Application in various domains delivered \n   ✅    High Quality Portfolio of work \n   ✅   5 star profile rating \n   ✅   93% Client Recommendation \n   ✅   More than 50%, client repetition ratio\n\nI do offer below services:\n\nApps \n\n    • Social Networking Apps \n    • Education: Schools, Colleges, Universities \n    • Chat Apps \n    • Dating Apps \n    • Health & Fitness Apps \n    • Food & Drink Apps \n    • Navigation Apps \n    • Photo Editing & Sharing Apps \n    • Photo & Video Apps \n    • Travel Apps \n    • Utility Apps \n    • Event Apps \n    • Coupon based Apps \n\nFrameworks, APIs \n\n    • iOS , Android, Windows\n    • Web Service ( Restful, Django, Ruby on Rails,PHP, JSON, XML, SOAP, Parse, Google App engine framework) \n    • In App Purchase \n    • Push Notification \n    • Face book API, Twitter API, LinkedIn API, Google+ API \n    • Google API,GeoLocation, Instagram API, Youtube API \n    • Flurry, Test flight \n    • MySQL, SQLite\n\nWebsite Development \n   • Wordpress theme implementation\n   • HTML5, CSS3, Bootstrap4\n   • JQuery, PHP, MVC\n\nOther: \n\n   • AppStore submission, testing, TestFlight, Unit Test \n   • Git, SVN, GitHub, bitBucket, bug trackers\n    ",
        "upporti18n": "\n          Taimur I.\n        \n        has worked\n      ",
        "air3btn8": "\n        26 jobs related to your search\n      ",
        "Avatar9": "https://assets.static-upwork.com/org-logo/646590785366704128",
        "textbasesm": "Associated with",
        "Name10": "\n          Smart Apps Planet\n        ",
        "dflex": "$500K+",
        "air3tokenwrap11": "\n      React\n    "
    },
    {
        "Title": "\n            Top Rated Mobile App Developer | iOS Developer | Android Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~015603f8f0af4f6e07?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c15ccj_IWtzFCYbSnVAnGa0y1Ytfe6ETaWBhkadDwTw8_eiEBdcmDexCoDP9oTylJV",
        "Name": "\n            Pritesh P.\n          ",
        "Location": "\n          India\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$24",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $1M+ earned\n    ",
        "air3badge": "\n  Available now\n",
        "air3tokenwrap": "\n      Android\n    ",
        "air3tokenwrap2": "\n      Android App Development\n    ",
        "air3tokenwrap3": "\n      Flutter\n    ",
        "air3tokenwrap4": "\n      React Native\n    ",
        "air3tokenwrap5": "\n      PHP\n    ",
        "air3tokenwrap6": "\n      Swift\n    ",
        "air3tokenwrap7": "\n      Node.js\n    ",
        "air3token": "+9",
        "Description": "\n      🥇🥇🥇 𝗣𝗿𝗲𝗽𝗮𝗿𝗲 𝘁𝗼 𝗯𝗲 𝗱𝗮𝘇𝘇𝗹𝗲𝗱!🥇🥇🥇\n\n🏆 Behold, the 𝗧𝗢𝗣 𝗥𝗔𝗧𝗘𝗗 𝗣𝗟𝗨𝗦 🏆 in the realm of freelancers, with a prestigious spot in the \"𝗧𝗼𝗽 3%\" on Upwork! Our credentials speak volumes:\n\n✅ Over 20,000+ hours of dedicated work and counting.\n✅ Successfully completed 350+ projects, leaving a trail of satisfied clients.\n✅ A flawless 100% Job Success ratio – it's all about client satisfaction.\n✅ An impressive 99% of clients recommend us to others.\n✅ An astounding 90% of our clients keep coming back for more.\n✅ We bring over 12+ years of industry experience.\n✅ Delivering unparalleled, high-quality work that sets new standards.\n✅ Cutting-edge solutions that won't break the bank.\n✅ Verified proficiency in fluent English.\n\n🌟 Whether you're a 𝗦𝘁𝗮𝗿𝘁𝘂𝗽 extraordinaire, an 𝗘𝘀𝘁𝗮𝗯𝗹𝗶𝘀𝗵𝗲𝗱 𝗕𝘂𝘀𝗶𝗻𝗲𝘀𝘀 maven, or simply on the prowl for 𝗠𝗩𝗣 domination, you've found the ultimate source of 𝗛𝗶𝗴𝗵-𝗤𝘂𝗮𝗹𝗶𝘁𝘆 𝗦𝗲𝗿𝘃𝗶𝗰𝗲𝘀 at prices that won't give you sticker shock.\n\n🚀 Ready to embark on a journey towards success? Click that '𝗜𝗻𝘃𝗶𝘁𝗲 𝘁𝗼 𝗝𝗼𝗯' button, and let's chart a course for your project and your vision.\n\n𝗢𝘃𝗲𝗿 𝘁𝗵𝗲 𝗽𝗮𝘀𝘁 𝗱𝗲𝗰𝗮𝗱𝗲, 𝗜'𝘃𝗲 𝘄𝗶𝗲𝗹𝗱𝗲𝗱 𝗺𝘆 𝗲𝘅𝗽𝗲𝗿𝘁𝗶𝘀𝗲 𝘁𝗼 𝗰𝗿𝗮𝗳𝘁 𝗮 𝗱𝗶𝘃𝗲𝗿𝘀𝗲 𝗿𝗮𝗻𝗴𝗲 𝗼𝗳 𝗮𝗽𝗽𝘀\n🛎️ 𝗙𝗶𝗻𝘁𝗲𝗰𝗵 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Payment app, Budgeting app\n🛎️ 𝗛𝗲𝗮𝗹𝘁𝗵𝗰𝗮𝗿𝗲 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Telemedicine app, Health records app\n🛎️ 𝗘-𝗰𝗼𝗺𝗺𝗲𝗿𝗰𝗲 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Shopping app, Delivery tracking app\n🛎️ 𝗥𝗲𝗮𝗹 𝗘𝘀𝘁𝗮𝘁𝗲 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Property listing app, Mortgage calculator app\n🛎️ 𝗘𝗱𝘂𝗰𝗮𝘁𝗶𝗼𝗻 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: E-learning app, Quiz and assessment app\n🛎️ 𝗧𝗿𝗮𝘃𝗲𝗹 𝗮𝗻𝗱 𝗧𝗼𝘂𝗿𝗶𝘀𝗺 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Travel booking app, Tour guide app\n🛎️ 𝗙𝗼𝗼𝗱 𝗮𝗻𝗱 𝗥𝗲𝘀𝘁𝗮𝘂𝗿𝗮𝗻𝘁 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Food delivery app, Table reservation app\n🛎️ 𝗘𝗻𝘁𝗲𝗿𝘁𝗮𝗶𝗻𝗺𝗲𝗻𝘁 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Streaming app, Event ticketing app\n🛎️ 𝗔𝘂𝘁𝗼𝗺𝗼𝘁𝗶𝘃𝗲 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Car rental app, Vehicle tracking app\n🛎️ 𝗙𝗶𝘁𝗻𝗲𝘀𝘀 𝗮𝗻𝗱 𝗪𝗲𝗹𝗹𝗻𝗲𝘀𝘀 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Workout app, Nutrition tracking app\n🛎️ 𝗦𝗼𝗰𝗶𝗮𝗹 𝗡𝗲𝘁𝘄𝗼𝗿𝗸𝗶𝗻𝗴: Social media app, Dating app\n🛎️ 𝗧𝗿𝗮𝗻𝘀𝗽𝗼𝗿𝘁𝗮𝘁𝗶𝗼𝗻 𝗮𝗻𝗱 𝗟𝗼𝗴𝗶𝘀𝘁𝗶𝗰𝘀: Shipping and tracking app, Fleet management app\n🛎️ 𝗔𝗴𝗿𝗶𝗰𝘂𝗹𝘁𝘂𝗿𝗲: Crop management app, Weather forecasting app\n🛎️ 𝗠𝗮𝗻𝘂𝗳𝗮𝗰𝘁𝘂𝗿𝗶𝗻𝗴: Inventory management app, Quality control app\n🛎️ 𝗜𝗼𝗧 (𝗜𝗻𝘁𝗲𝗿𝗻𝗲𝘁 𝗼𝗳 𝗧𝗵𝗶𝗻𝗴𝘀) 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: IoT monitoring and control app\n🛎️ 𝗕𝗹𝗼𝗰𝗸𝗰𝗵𝗮𝗶𝗻 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Cryptocurrency wallet app and Blockchain Solutions\n🛎️ 𝗕𝗹𝘂𝗲𝘁𝗼𝗼𝘁𝗵 𝗔𝗽𝗽 𝗗𝗲𝘃𝗲𝗹𝗼𝗽𝗺𝗲𝗻𝘁: Bluetooth-based smart device control app\n🛎️ 𝗡𝗙𝗖 (𝗡𝗲𝗮𝗿 𝗙𝗶𝗲𝗹𝗱 𝗖𝗼𝗺𝗺𝘂𝗻𝗶𝗰𝗮𝘁𝗶𝗼𝗻) 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Mobile payment and contactless communication app\n🛎️ 𝗛𝗜𝗣𝗔𝗔 𝗖𝗼𝗺𝗽𝗹𝗶𝗮𝗻𝗰𝗲-𝗕𝗮𝘀𝗲𝗱 𝗛𝗲𝗮𝗹𝘁𝗵 𝗜𝗻𝗱𝘂𝘀𝘁𝗿𝘆: Electronic health records (EHR) app\n\n𝗪𝗵𝘆 𝘀𝗵𝗼𝘂𝗹𝗱 𝘆𝗼𝘂 𝗲𝗻𝘁𝗿𝘂𝘀𝘁 𝘆𝗼𝘂𝗿 𝗽𝗿𝗼𝗷𝗲𝗰𝘁 𝘁𝗼 𝗺𝗲?\n✅  I am your steadfast ally in your quest for success.\n✅  Uncompromising commitment to quality without breaking the bank.\n✅  A robust command of Android, iPhone, and backend architecture, alongside database wizardry.\n✅  Crafting applications that seamlessly adapt to all devices.\n✅  Promising on-time delivery or even before.\n✅  A perpetual thirst for the latest technological innovations.\n\n𝗠𝘆 𝗰𝗼𝗿𝗲 𝘀𝗸𝗶𝗹𝗹𝘀 𝗮𝗻𝗱 𝗲𝘅𝗽𝗲𝗿𝗶𝗲𝗻𝗰𝗲𝘀 𝗮𝗿𝗲 𝗮 𝗳𝗼𝗿𝗰𝗲 𝘁𝗼 𝗯𝗲 𝗿𝗲𝗰𝗸𝗼𝗻𝗲𝗱 𝘄𝗶𝘁𝗵\n🎯  Mastering the art of backend interaction: Rest API, JSON, XML, PHP, Node.js, Python.\n🎯  Databases and data management aficionado: SQLite, MySQL, Parse, MongoDB.\n🎯  Seamless social integration: Facebook, Twitter, Youtube, Instagram, Snapchat, Tinder.\n🎯  Real-time chat maestro: XMPP, Socket, Firebase, GetStream, Twilio.\n🎯  Version control expert: Github, Bitbucket, Gitlab.\n🎯  Navigating the world with Google and Apple Maps, Geolocation, GPS, and Location Tracking.\n🎯  Making waves in audio and video live streaming.\n🎯  Mastery of Firebase APIs.\n🎯  Navigating the payment landscape with ease: Paypal, Braintree, Stripe Payment Gateway.\n🎯  Scanning the horizon with QR Codes, Bar Codes, VIN Scanner, and NFC Tags Reading.\n🎯  Engaging users with In-App Purchase, Advertisement, Push Notifications, GCM, and Google Analytics.\n🎯  Elevating photo and video sharing with editing and filters.\n\n𝗜 𝗵𝗮𝗿𝗻𝗲𝘀𝘀 𝘁𝗵𝗲 𝗽𝗼𝘄𝗲𝗿 𝗼𝗳 𝘁𝗵𝗲𝘀𝗲 𝗰𝘂𝘁𝘁𝗶𝗻𝗴-𝗲𝗱𝗴𝗲 𝘁𝗲𝗰𝗵𝗻𝗼𝗹𝗼𝗴𝗶𝗲𝘀\n📌  Android: Kotlin, Java\n📌  iOS: Swift, Objective-C\n📌  Cross-platform (Hybrid): Flutter (Dart) , React Native (Javascript)\n📌  Web / Backend: PHP, Node.js, Python, Laravel, WordPress, Express.js, Nest.js, Django\n📌  Frontend: React.js, HTML5, CSS3, BootStrap, JavaScript, jQuery\n📌  Exploring the realms of AI, Internet Of Things (IoT), Beacons, and Ricoh Theta 360.\n    ",
        "upporti18n": "\n          Pritesh P.\n        \n        has worked\n      ",
        "air3btn8": "\n        67 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      iOS Development\n    "
    },
    {
        "Title": "\n            Android App Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~017055103a7806ae57?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1PiXGIJrEoQ5vETncizHBXNL9SzTjUw0u5oUYsQyu2G0jjxsyvtTHkZ-JljMH82Fr",
        "Name": "\n            Mahbub A.\n          ",
        "Location": "\n          Bangladesh\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$25",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $6K+ earned\n    ",
        "air3badge": "",
        "air3tokenwrap": "\n      Smartphone\n    ",
        "air3tokenwrap2": "\n      Android\n    ",
        "air3tokenwrap3": "\n      Android App Development\n    ",
        "air3tokenwrap4": "\n      Android SDK\n    ",
        "air3tokenwrap5": "\n      Android Studio\n    ",
        "air3tokenwrap6": "\n      Java\n    ",
        "air3tokenwrap7": "\n      Kotlin\n    ",
        "air3token": "+9",
        "Description": "\n      Hello! My name is Mahbub Alam, and I am an experienced Android app developer with a passion for creating innovative, high-quality applications. Over the years, I have worked on a wide range of projects, both as a solo developer and as part of large teams.\n\nOne of my greatest strengths as a developer is my proactive and communicative approach. I understand the importance of clear feedback, both in terms of providing feedback to improve app functionality and design, and responding to client feedback in a timely and effective manner. By staying in close communication with my clients and team members, I am able to deliver results that consistently exceed expectations.\n\nMy usual stack includes a range of powerful and popular tools, such as MVVM architecture pattern, Java, Kotlin, Retrofit, Volley, Room, and LiveData. With my proficiency in these tools, I am able to create Android applications that are both efficient and user-friendly, with a focus on responsiveness and reliability.\n\nIn all my work, my goal is to create applications that are both functional and beautiful, and that meet the needs of my clients and end-users. With my experience, technical skills, and strong communication abilities, I am confident in my ability to take on any Android app development project and deliver outstanding results.\n\nI have 5+ years of experience as a Professional android app developer. I worked on 150+ projects, like,\no\tVPN, \no\teCommerce Stores \no\tA Messenger With Chat And Call \no\tDating Apps\no\tLive TV\no\tVideo Player\no\tWallpaper\no\tPDF maker\no\tPDF Reader \no\tLocker, \no\tReminder, etc \nI ensure you that you will get a high-quality premium app. I also provide any type of custom app. So don't hesitate to contact me for free advice or help regarding your android development project.\n\nServices I Can Provide\n\n•\tAndroid app development using MVVM  \n•\tComplete Development of the android app\n•\tApp Riskin\n•\tBug Fixe\n•\tAndroid API Support\n•\tGoogle maps integration\n•\tFirebase complete project setup\n•\tFirebase Database\n•\tSQLite Database\n•\tREST API\n•\tAuthentication using Gmail, Facebook, Phone, etc\n•\tPayment gateways\n•\tPush Notification\n•\tResponsive Screen \n•\tMaterial Design\n•\tApp Purchases\n•\tApp Monetization (Admob, AppLovin, Facebook, etc ads integration)\n•\tAndroid TV App\n\n\nDevelopment Process \n\n•\tCollect & Analyze Client Requirements\n•\tDesign \n•\tIcon Design\n•\tDevelopment \n•\tQA & Testing \n•\tMaintenance & Support\n\n\n\n\nWhy Choose me?\n\n•\tTop-quality premium service\n•\t30 days of free support after development\n•\tI am available 24/7 as an android app developer\n•\tFree Technical support all the time \n•\tTest your app\n•\tQuality Guidelines\n\nSo I will be your best android app developer for perfect android app development.\n\n\n\n    ",
        "upporti18n": "\n          Mahbub A.\n        \n        has worked\n      ",
        "air3btn8": "\n        15 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      Mobile App Development\n    "
    },
    {
        "Title": "\n            Top Rated Plus iOS/Android Developer\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~017def607c50982057?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c18zySm-AjdfUh3ql9ko9jZt47PVluIpQifl5CAfrepxgIjvyaGTG1ePyPevqX5ket",
        "Name": "\n            Shahrukh J.\n          ",
        "Location": "\n          India\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$15",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $200K+ earned\n    ",
        "air3badge": "\n  Available now\n",
        "air3tokenwrap": "\n      Android\n    ",
        "air3tokenwrap2": "\n      Android App Development\n    ",
        "air3tokenwrap3": "\n      Android Studio\n    ",
        "air3tokenwrap4": "\n      Java\n    ",
        "air3tokenwrap5": "\n      Kotlin\n    ",
        "air3tokenwrap6": "\n      Mobile App Development\n    ",
        "air3tokenwrap7": "\n      iOS Development\n    ",
        "air3token": "+11",
        "Description": "\n      Hi, I am Shahrukh, a senior mobile app developer rewarded as a Top Rated Plus by Upwork (Top 3%) \n\nWith expertise from 7 years, I excel in crafting mobile applications for iOS and Android platforms including Native and Hybrid technologies. \n\nWhat you can expect from me:\n• Quality: I make sure your app works as you expect it to work. I will make suggestions to ensure you get the best results. I write readable and maintainable code.\n• Good communication: I will let you know what I’m working on in fluent English.\n• Honesty: I will not accept any job until I fully understand what’s expected of me. If anything doesn’t go as expected I will instantly let you know. I will not deliver any half-baked products.\n• Speed: I will meet and often beat the agreed-upon deadline.\n\nI'm open to working as a part or lead of the team or as an individual developer as I already did in the past.\n\nDomains on which I developed apps\n-------------------------------------------------\nOn-Demand Marketplace\nUtility\nSocial networking/Chat/messaging\nMini-games\nE-commerce\nBluetooth/beacons\nTaxi/booking\nFitness/health\nTravel\nIoT\n\nCoding Strategy:\n-------------------------\n*Well-optimized, clean, robust, and well-commented code with qualified naming conventions.\n* Multi-Language Support \n* Localization And Internationalization support \n* API /Web Service Integration \n\nIf you need top-tier expertise and a proven track record for your projects, I am here to help. Let's create something remarkable together.\n\n    ",
        "upporti18n": "\n          Shahrukh J.\n        \n        has worked\n      ",
        "air3btn8": "\n        15 jobs related to your search\n      ",
        "Avatar9": "https://assets.static-upwork.com/org-logo/425209229683789824",
        "textbasesm": "Associated with",
        "Name10": "\n          OnGraph Technologies Private Limited\n        ",
        "dflex": "$10M+",
        "air3tokenwrap11": "\n      Firebase\n    "
    },
    {
        "Title": "\n            Senior Flutter Developer | Mobile App Developer | Android & iOS App\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~0128868d1393e9ab4e?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c18xMT6AJePz_95tkey5_eBEQ5hGGF4gniTKtLiCwQ8BoJe1BCbVVJvcGz6Vh52K2J",
        "Name": "\n            Zeeshan A.\n          ",
        "Location": "\n          Pakistan\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$20",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $30K+ earned\n    ",
        "air3badge": "",
        "air3tokenwrap": "\n      Android App Development\n    ",
        "air3tokenwrap2": "\n      Mobile App Development\n    ",
        "air3tokenwrap3": "\n      Hybrid App Development\n    ",
        "air3tokenwrap4": "\n      iOS Development\n    ",
        "air3tokenwrap5": "\n      Firebase\n    ",
        "air3tokenwrap6": "\n      RESTful API\n    ",
        "air3tokenwrap7": "\n      Flutter Stack\n    ",
        "air3token": "+9",
        "Description": "\n      Looking for a skilled and dedicated Mobile App Developer specializing in Flutter with a proven track record of delivering high-quality solutions? Look no further!\n\nHere is why:\n✅ 🏆 𝗧𝗢𝗣 𝗥𝗔𝗧𝗘𝗗 𝗣𝗟𝗨𝗦 🏆 by Upwork (𝗧𝗼𝗽 𝟯%)\n✅ 4+ years of experience in Mobile App Development\n✅ 100% Job Success (Client Satisfaction Ratio)\n✅ 1200+ hours logged\n✅ Budget-friendly\n✅ Fluent English & Prompt Communication\n\nIf you're looking for a dedicated full-time freelancer who consistently delivers quality work with a problem-solving attitude, let's connect! \n\nClick on the '𝗜𝗻𝘃𝗶𝘁𝗲 𝘁𝗼 𝗝𝗼𝗯' button to discuss your project in detail and explore how we can bring your vision to life together. I'm excited to learn more about your needs and show you how I can add value.\n----------------------------------------------\n𝗪𝗵𝗮𝘁 𝗺𝘆 𝗰𝗹𝗶𝗲𝗻𝘁𝘀 𝘀𝗮𝘆?\n\n𝙕𝙚𝙚𝙨𝙝𝙖𝙣 𝙞𝙨 𝙝𝙖𝙧𝙙𝙬𝙤𝙧𝙠𝙞𝙣𝙜 𝙖𝙣𝙙 𝙑𝙖𝙡𝙪𝙚𝙨 𝙘𝙪𝙨𝙩𝙤𝙢𝙚𝙧 𝙝𝙞𝙜𝙝𝙡𝙮. 𝙄 𝙝𝙖𝙫𝙚 𝙛𝙚𝙡𝙩 𝙝𝙚 𝙨𝙩𝙧𝙞𝙫𝙚𝙨 𝙛𝙤𝙧 𝙥𝙚𝙧𝙛𝙚𝙘𝙩𝙞𝙤𝙣 𝙖𝙣𝙙 𝙖𝙗𝙡𝙚 𝙩𝙤 𝙧𝙚𝙬𝙤𝙧𝙠 𝙪𝙣𝙩𝙞𝙡 𝙜𝙤𝙖𝙡𝙨 𝙖𝙧𝙚 𝙢𝙚𝙩\n- 𝑨𝒏𝒊𝒔𝒉 𝑵𝑹𝑲 ⭐⭐⭐⭐⭐\n\n𝘼𝙝𝙢𝙖𝙙’𝙨 𝙖𝙩𝙩𝙚𝙣𝙩𝙞𝙤𝙣 𝙩𝙤 𝙙𝙚𝙩𝙖𝙞𝙡, 𝙘𝙤𝙢𝙢𝙞𝙩𝙢𝙚𝙣𝙩 𝙩𝙤 𝙚𝙭𝙘𝙚𝙡𝙡𝙚𝙣𝙘𝙚, 𝙖𝙣𝙙 𝙥𝙧𝙤𝙗𝙡𝙚𝙢-𝙨𝙤𝙡𝙫𝙞𝙣𝙜 𝙖𝙗𝙞𝙡𝙞𝙩𝙞𝙚𝙨 𝙢𝙖𝙠𝙚 𝙝𝙞𝙢 𝙖𝙣 𝙤𝙪𝙩𝙨𝙩𝙖𝙣𝙙𝙞𝙣𝙜 𝙛𝙧𝙚𝙚𝙡𝙖𝙣𝙘𝙚𝙧. 𝙄 𝙝𝙞𝙜𝙝𝙡𝙮 𝙧𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙 𝘼𝙝𝙢𝙖𝙙 𝙩𝙤 𝙖𝙣𝙮𝙤𝙣𝙚 𝙞𝙣 𝙣𝙚𝙚𝙙 𝙤𝙛 𝙖 𝙧𝙚𝙡𝙞𝙖𝙗𝙡𝙚 𝙖𝙣𝙙 𝙩𝙖𝙡𝙚𝙣𝙩𝙚𝙙 𝙖𝙥𝙥 𝙙𝙚𝙫𝙚𝙡𝙤𝙥𝙚𝙧. 𝙄 𝙡𝙤𝙤𝙠 𝙛𝙤𝙧𝙬𝙖𝙧𝙙 𝙩𝙤 𝙬𝙤𝙧𝙠𝙞𝙣𝙜 𝙬𝙞𝙩𝙝 𝙝𝙞𝙢 𝙤𝙣 𝙛𝙪𝙩𝙪𝙧𝙚 𝙥𝙧𝙤𝙟𝙚𝙘𝙩𝙨.\n- 𝑻𝒂𝒐𝒖𝒇𝒊𝒄 𝑮𝒂𝒏𝒅𝒊 ⭐⭐⭐⭐⭐\n----------------------------------------------\n𝗪𝗵𝗮𝘁 𝘀𝗲𝘁𝘀 𝗺𝗲 𝗮𝗽𝗽𝗮𝗿𝘁?\n\n💥 𝗣𝗿𝗼𝘃𝗲𝗻 𝗧𝗿𝗮𝗰𝗸 𝗥𝗲𝗰𝗼𝗿𝗱: I've delivered 20+ projects with high client satisfaction rates and positive feedback.\n💥 𝗖𝗼𝗺𝗺𝘂𝗻𝗶𝗰𝗮𝘁𝗶𝗼𝗻: Effective communication is key to success. I'm responsive, attentive, and open to your ideas throughout the project.\n💥 𝗣𝗿𝗼𝗯𝗹𝗲𝗺-𝗦𝗼𝗹𝘃𝗶𝗻𝗴: I tackle challenges with a solutions-oriented mindset, finding efficient ways to meet project objectives.\n----------------------------------------------\n𝗛𝗲𝗿𝗲'𝘀 𝗺𝘆 𝘀𝘁𝗿𝗲𝗮𝗺𝗹𝗶𝗻𝗲𝗱 𝗽𝗿𝗼𝗰𝗲𝘀𝘀 𝘁𝗼 𝗯𝘂𝗶𝗹𝗱 𝘆𝗼𝘂𝗿 𝗮𝗽𝗽:\n\n✅ 𝗥𝗲𝗾𝘂𝗶𝗿𝗲𝗺𝗲𝗻𝘁𝘀 𝗚𝗮𝘁𝗵𝗲𝗿𝗶𝗻𝗴: I ensure a thorough understanding of your needs.\n✅ 𝗨𝗜/𝗨𝗫 𝗗𝗲𝘀𝗶𝗴𝗻: Crafting intuitive designs using Figma or XD for your approval.\n✅ 𝗗𝗲𝘃𝗲𝗹𝗼𝗽𝗺𝗲𝗻𝘁: Creating the app, integrating REST APIs, and setting up databases (Firebase, SupaBase, MongoDB etc).\n✅ 𝗧𝗲𝘀𝘁𝗶𝗻𝗴 & 𝗙𝗲𝗲𝗱𝗯𝗮𝗰𝗸 𝗟𝗼𝗼𝗽: Delivering a functional version for your review and feedback.\n✅ 𝗙𝗶𝗻𝗮𝗹 𝗟𝗼𝗼𝗽: Making necessary adjustments and delivering the polished app for launch.\n----------------------------------------------\n𝗪𝗵𝗮𝘁 𝗰𝗮𝗻 𝘆𝗼𝘂 𝗲𝘅𝗽𝗲𝗰𝘁 𝗳𝗿𝗼𝗺 𝗺𝗲?\n\nWith 4+ years in Mobile app development and a CS background, I've crafted 20+ apps and I can develop the following apps:\n\n✔ Food delivery app\n✔ On-demand app\n✔ Home services app\n✔ Handyman app\n✔ Marketplace app\n✔ Salon app\n✔ Beauty app\n✔ Taxi app\n✔ Ride app\n✔ E-commerce app\n✔ Health and fitness app\n✔ Travel app\n✔ Live Streaming app\n✔ Video streaming app\n✔ Finance app\n✔ Shopping app\n✔ Telemedicine app\n✔ Real estate app\n✔ Social media app\n✔ Messaging app\n✔ AI Chatbot\n✔ AI Wellness app\n✔ AI Learning app\n----------------------------------------------\n𝐖𝐡𝐚𝐭 𝐘𝐨𝐮'𝐥𝐥 𝐆𝐚𝐢𝐧 𝐟𝐫𝐨𝐦 𝐂𝐨𝐥𝐥𝐚𝐛𝐨𝐫𝐚𝐭𝐢𝐧𝐠 𝐰𝐢𝐭𝐡 𝐌𝐞:\n\n✔ Custom Flutter Mobile App Developer\n✔ Flutter Mobile App Developer for IoT Mobile App\n✔ Flutter Mobile App Developer for Artificial Intelligence Mobile App\n✔ Flutter Mobile App Developer for Security Mobile App\n✔ Flutter Mobile App Developer for Digital Agency Mobile App\n✔ Flutter Mobile App Developer for Construction Mobile App\n✔ Flutter Mobile App Developer for Savings Mobile App\n✔ Flutter Mobile App Developer for Payment Transfer Mobile App\n✔ Flutter Mobile App Developer for Clothes Shop Mobile App\n✔ Flutter Mobile App Developer for School Mobile App\n✔ Flutter Android / iOS app\n✔ Flutter Bug Fixings\n----------------------------------------------\nIf you're searching for a skilled and dedicated Mobile App Developer specializing in Flutter with a proven track record of delivering high-quality solutions, I'm eager to join your project and contribute to its success.\n\n🚀If you have any queries, message me on my profile for a good conversation or we can hop on a quick call to discuss your project.\n\n❗❗ Check out my portfolio! ❗❗\n\n(The testimonials are from Upwork client feedback, all of them are available below.)\n    ",
        "upporti18n": "\n          Zeeshan A.\n        \n        has worked\n      ",
        "air3btn8": "\n        3 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      Flutter\n    "
    },
    {
        "Title": "\n            Mobile App Engineer | Android & iOS Native | Kotlin | Swift\n          ",
        "Title_URL": "https://www.upwork.com/freelancers/~015291a52b8ecdb3ef?referrer_url_path=/nx/search/talent/",
        "Avatar": "https://www.upwork.com/profile-portraits/c1qt-Szp65vAKosBqRGoW3WQkfSACmD9io8b_fgKSA_FiYxMn1ZVS5qQvlOV3FuR-7",
        "Name": "\n            Nikola G.\n          ",
        "Location": "\n          Serbia\n        ",
        "air3btn": "\n    View profile\n  ",
        "Price": "$35",
        "detailsitem": "/hr",
        "air3progresscircle": "\n          100%\n        ",
        "air3progresscircle1": "Job Success",
        "air3poppertrigger": "\n      $30K+ earned\n    ",
        "air3badge": "",
        "air3tokenwrap": "\n      Smartphone\n    ",
        "air3tokenwrap2": "\n      Android\n    ",
        "air3tokenwrap3": "\n      Android App Development\n    ",
        "air3tokenwrap4": "\n      Android SDK\n    ",
        "air3tokenwrap5": "\n      Android Studio\n    ",
        "air3tokenwrap6": "\n      Java\n    ",
        "air3tokenwrap7": "\n      Kotlin\n    ",
        "air3token": "+10",
        "Description": "\n      - Full-stack Mobile App development\n- Android Native\n- iOS Native\n- Kotlin\n- Swift\n- UI/UX\n- Figma\n- Jetpack Compose\n- SwiftUI\n- Firebase\n- Node\n\n    ",
        "upporti18n": "\n          Nikola G.\n        \n        has worked\n      ",
        "air3btn8": "\n        10 jobs related to your search\n      ",
        "Avatar9": "",
        "textbasesm": "",
        "Name10": "",
        "dflex": "",
        "air3tokenwrap11": "\n      Mobile App Development\n    "
    }
]