// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYg4dZjo0r1CR8SKMLA8GupluCJEfcPmE',
    appId: '1:572870971203:web:3afc317f03af87b4bb69f6',
    messagingSenderId: '572870971203',
    projectId: 'peacify-cf1a5',
    authDomain: 'peacify-cf1a5.firebaseapp.com',
    storageBucket: 'peacify-cf1a5.firebasestorage.app',
    measurementId: 'G-3MNYVT6378',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP4BuqG4n-eJ1jZ3U2zlr1ZC6F6iqFFDo',
    appId: '1:572870971203:android:1943afcd5e6f591bbb69f6',
    messagingSenderId: '572870971203',
    projectId: 'peacify-cf1a5',
    storageBucket: 'peacify-cf1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZe67yzPjMDyr-jWlwPPNOjTiwSkDvqwc',
    appId: '1:572870971203:ios:cf7cd926b1861937bb69f6',
    messagingSenderId: '572870971203',
    projectId: 'peacify-cf1a5',
    storageBucket: 'peacify-cf1a5.firebasestorage.app',
    iosBundleId: 'com.example.peacify',
  );
}
