# Generated by Django 5.1.4 on 2025-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donateditem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='img',
            field=models.ImageField(blank=True, default='images/default_request_img.png', help_text='Provide a picture of organization/needy', upload_to=''),
        ),
    ]
