# Generated by Django 5.1.4 on 2025-01-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
