# Generated by Django 5.1.4 on 2025-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_chatmessage_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
