# Generated by Django 5.1.4 on 2025-01-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('donations', '0009_alter_chatmessage_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='item',
        ),
        migrations.AddField(
            model_name='donation',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
