# Generated by Django 5.1.4 on 2025-01-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_location_alter_customer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
