# Generated by Django 5.1.4 on 2025-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_remove_customer_location_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
